name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: noisemodelling
          POSTGRES_PASSWORD: noisemodelling
          POSTGRES_DB: noisemodelling_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Building
        run: mvn test install -B
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and test WPS with Gradle
        run:  ./gradlew build --info --stacktrace
        working-directory: ./wps_scripts
      - name: Deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        if: ${{ (env.MAVEN_USERNAME != null) && (github.ref == 'refs/heads/main') }}
        run: mvn clean deploy -B -P maven-deploy
      - name: Clean
        run: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.m2/
            $HOME/.gradle/caches/
            $HOME/.gradle/wrapper/
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      #Production of the archive
      - name: Unzip production artifacts
        run: cd wps_scripts && ./gradlew assembleDist && unzip build/distributions/scriptrunner.zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NoiseModelling_without_gui
          path: wps_scripts/scriptrunner/
